# Generated by Django 4.2 on 2024-12-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app.cita'),
        ),
    ]
